services:
  postgres:
    image: postgres:latest
    container_name: reservations-postgres
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: reservations_user
      POSTGRES_PASSWORD: reservations_pass
    ports:
      - "5432:5432"