spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/reservations_db
    user: reservations_user
    password: reservations_pass
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations_db
    username: reservations_user
    password: reservations_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.flywaydb: INFO