version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: reservations-postgres
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: reservations_user
      POSTGRES_PASSWORD: reservations_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: